{
        "sysAutomaticTotal": 16,
        "sysManualTotal": 45,
        "sysPercent": 0.26,
        "dataTableAutomaticTotal": 925,
        "dataTableManualTotal": 3267,
        "dataTablePercent": 0.22,
        "dataItemAutomaticTotal": 25802,
        "dataItemManualTotal": 91725,
        "dataItemPercent": 0.22,
        "metadataAutomaticTotal": 2593,
        "metadataManualTotal": 1825,
        "metadataPercent": 0.59,
        "ministryDataItemCompareAutomaticTotal": 14283,
        "ministryDataItemCompareManualTotal": 32843,
        "ministryDataItemComparePercent": 0.3,
        "provincialCodeCompareAutomaticTotal": 23853,
        "provincialCodeCompareManualTotal": 129434,
        "provincialCodeComparePercent": 0.16,
        "localSysTotal": 493,
        "localDataTableTotal": 33,
        "localDataItemTotal": 23159,
        "ministryDataItemTotal": 16709,
        "ministryCodeTotal": 66125
      }